const CONFIG = {
  GEMINI_MODEL: 'gemini-2.5-flash',
  GEMINI_API_KEY_PROPERTY: 'GEMINI_API_KEY',
  DRIVE_ROOT_FOLDER_PREFIX: 'Taxes',
  DRIVE_INVOICES_FOLDER: 'Invoices',
  SHEET_NAME: 'Deductibles',
  PROCESSED_LABEL: 'tax/processed',
  LAST_PROCESSED_PROPERTY: 'LAST_PROCESSED_TIMESTAMP',
  SHEET_ID_PROPERTY: 'SHEET_ID',
  TRIGGER_HOUR: 0,
  DEBUG_LOOKBACK_HOURS: 1,
};
