const CONFIG = {
  GEMINI_MODEL: 'gemini-2.5-flash',
  GEMINI_API_KEY_PROPERTY: 'GEMINI_API_KEY',
  DRIVE_FOLDER_NAME: 'Tax Receipts',
  SHEET_NAME: 'Tax Deductions',
  PROCESSED_LABEL: 'tax/processed',
  LAST_PROCESSED_PROPERTY: 'LAST_PROCESSED_TIMESTAMP',
  SHEET_ID_PROPERTY: 'SHEET_ID',
  TRIGGER_INTERVAL_HOURS: 1,
  DEBUG_LOOKBACK_HOURS: 1,
};
